
import { University, StudentAmbassador, Review } from './types';

export const universities: University[] = [
  {
    id: 'u1',
    name: 'Delhi University',
    logo: 'https://images.unsplash.com/photo-1594312915251-48db9280c8f1?auto=format&fit=crop&q=80&w=300&h=300',
    location: 'New Delhi, India',
    country: 'India',
    accreditation: 'UGC A++',
    rating: 4.7,
    tuitionFees: {
      undergraduate: '$1,200 - $3,000 per year',
      postgraduate: '$1,800 - $4,500 per year',
    },
    programs: [
      'Computer Science',
      'Business Administration',
      'Engineering',
      'Medicine',
      'Arts and Humanities',
    ],
    admissionRequirements: [
      'High school diploma or equivalent',
      'Minimum GPA of 3.0',
      'Entrance examination',
      'English proficiency test (IELTS/TOEFL)',
    ],
    scholarships: [
      'Merit-based scholarships',
      'Need-based financial aid',
      'International student scholarships',
    ],
    description: 'Delhi University is one of the premier educational institutions in India, known for its excellent academic programs and vibrant campus life.',
    campusLife: 'The university offers a rich campus life with numerous clubs, sports facilities, cultural events, and student organizations.',
    studentCount: 25000,
    establishedYear: 1922,
    facilities: [
      'Modern libraries',
      'Computer labs',
      'Sports complexes',
      'Student hostels',
      'Research centers',
    ],
    website: 'https://www.du.ac.in',
    contactEmail: 'admissions@du.ac.in',
    featured: true,
  },
  {
    id: 'u2',
    name: 'Indian Institute of Technology (IIT) Bombay',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&q=80&w=300&h=300',
    location: 'Mumbai, India',
    country: 'India',
    accreditation: 'UGC A++',
    rating: 4.9,
    tuitionFees: {
      undergraduate: '$2,000 - $4,500 per year',
      postgraduate: '$2,500 - $5,500 per year',
    },
    programs: [
      'Engineering',
      'Computer Science',
      'Technology Management',
      'Design',
      'Applied Sciences',
    ],
    admissionRequirements: [
      'High school diploma with strong STEM background',
      'JEE Advanced entrance examination',
      'GATE for postgraduate programs',
      'English proficiency',
    ],
    scholarships: [
      'Merit scholarships',
      'Research assistantships',
      'Industry-sponsored scholarships',
      'Government fellowships',
    ],
    description: 'IIT Bombay is internationally recognized for excellence in engineering and technology education and is consistently ranked among the top technical institutions worldwide.',
    campusLife: 'The campus provides a blend of academic rigor and extracurricular engagement, with cultural festivals, technical competitions, and sports events.',
    studentCount: 10000,
    establishedYear: 1958,
    facilities: [
      'Cutting-edge research laboratories',
      'Innovation centers',
      'Incubation hubs',
      'Olympic-sized swimming pool',
      'Modern dormitories',
    ],
    website: 'https://www.iitb.ac.in',
    contactEmail: 'admissions@iitb.ac.in',
    featured: true,
  },
  {
    id: 'u3',
    name: 'University of Mumbai',
    logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=300&h=300',
    location: 'Mumbai, India',
    country: 'India',
    accreditation: 'UGC A+',
    rating: 4.5,
    tuitionFees: {
      undergraduate: '$1,000 - $2,500 per year',
      postgraduate: '$1,500 - $3,500 per year',
    },
    programs: [
      'Business Studies',
      'Computer Applications',
      'Science and Technology',
      'Arts and Social Sciences',
      'Law',
    ],
    admissionRequirements: [
      'Secondary school certificate',
      'Higher secondary certificate with minimum 50%',
      'Entrance examinations for specific programs',
      'English proficiency certification',
    ],
    scholarships: [
      'Academic excellence scholarships',
      'Minority student scholarships',
      'Sports scholarships',
      'Cultural achievement scholarships',
    ],
    description: 'The University of Mumbai is one of India\'s oldest and most prestigious institutions, renowned for its diverse academic offerings and rich historical legacy.',
    campusLife: 'Students enjoy a dynamic campus life with numerous student societies, cultural events, and sports competitions.',
    studentCount: 35000,
    establishedYear: 1857,
    facilities: [
      'Historic libraries',
      'Digital learning centers',
      'Sports grounds',
      'Performing arts theaters',
      'Student housing',
    ],
    website: 'https://www.mu.ac.in',
    contactEmail: 'info@mu.ac.in',
  },
  {
    id: 'u4',
    name: 'Indian Institute of Management (IIM) Ahmedabad',
    logo: 'https://images.unsplash.com/photo-1557426272-fc759fdf7a8d?auto=format&fit=crop&q=80&w=300&h=300',
    location: 'Ahmedabad, India',
    country: 'India',
    accreditation: 'AACSB, EQUIS',
    rating: 4.9,
    tuitionFees: {
      undergraduate: 'N/A',
      postgraduate: '$15,000 - $20,000 per year',
    },
    programs: [
      'MBA',
      'Executive MBA',
      'PhD in Management',
      'Executive Education',
      'Business Analytics',
    ],
    admissionRequirements: [
      'Bachelor\'s degree with minimum 55%',
      'CAT/GMAT score',
      'Work experience (for executive programs)',
      'Personal interview and group discussion',
    ],
    scholarships: [
      'Need-based financial aid',
      'Corporate-sponsored scholarships',
      'Alumni endowments',
      'Government scholarships for reserved categories',
    ],
    description: 'IIM Ahmedabad is consistently ranked as India\'s top business school, known for its case-based teaching methodology and distinguished faculty.',
    campusLife: 'The campus offers a rigorous yet rewarding experience with business competitions, leadership forums, and entrepreneurial initiatives.',
    studentCount: 1200,
    establishedYear: 1961,
    facilities: [
      'Harvard-style classrooms',
      'Management library',
      'Entrepreneurship center',
      'Executive training centers',
      'Modern residential facilities',
    ],
    website: 'https://www.iima.ac.in',
    contactEmail: 'admissions@iima.ac.in',
    featured: true,
  },
  {
    id: 'u5',
    name: 'Manipal University',
    logo: 'https://images.unsplash.com/photo-1592841644108-9e4562431c68?auto=format&fit=crop&q=80&w=300&h=300',
    location: 'Manipal, Karnataka, India',
    country: 'India',
    accreditation: 'UGC A+',
    rating: 4.6,
    tuitionFees: {
      undergraduate: '$5,000 - $9,000 per year',
      postgraduate: '$6,000 - $11,000 per year',
    },
    programs: [
      'Medicine',
      'Engineering',
      'Pharmacy',
      'Architecture',
      'Communication',
    ],
    admissionRequirements: [
      'High school completion with science background',
      'Manipal entrance test',
      'NEET for medical programs',
      'Portfolio for design programs',
    ],
    scholarships: [
      'Academic merit scholarships',
      'Sports excellence scholarships',
      'International student grants',
      'Research scholarships',
    ],
    description: 'Manipal University is a private research institution known for its health sciences and technical programs, with a global outlook on education.',
    campusLife: 'The self-contained campus offers modern amenities, international exposure, and numerous extracurricular opportunities.',
    studentCount: 28000,
    establishedYear: 1953,
    facilities: [
      'Teaching hospital',
      'Innovation center',
      'International collaborations',
      'Olympic-standard sports facilities',
      'On-campus housing',
    ],
    website: 'https://www.manipal.edu',
    contactEmail: 'admissions@manipal.edu',
  },
  {
    id: 'u6',
    name: 'All India Institute of Medical Sciences (AIIMS)',
    logo: 'https://images.unsplash.com/photo-1631815588090-d4bfec5b9896?auto=format&fit=crop&q=80&w=300&h=300',
    location: 'New Delhi, India',
    country: 'India',
    accreditation: 'Medical Council of India',
    rating: 4.9,
    tuitionFees: {
      undergraduate: '$1,000 - $2,000 per year',
      postgraduate: '$1,500 - $3,000 per year',
    },
    programs: [
      'MBBS',
      'MD/MS',
      'M.Ch/DM',
      'Nursing',
      'Paramedical Sciences',
    ],
    admissionRequirements: [
      'NEET qualification',
      'High school with strong science background',
      'Entrance examination',
      'Interview process',
    ],
    scholarships: [
      'Government subsidies',
      'Merit scholarships',
      'Research grants',
      'Financial assistance for underprivileged students',
    ],
    description: 'AIIMS is India\'s premier medical institution offering world-class medical education and patient care facilities.',
    campusLife: 'The campus provides a conducive environment for medical studies with clinical exposure, research opportunities, and professional development activities.',
    studentCount: 3000,
    establishedYear: 1956,
    facilities: [
      'State-of-the-art hospitals',
      'Advanced research labs',
      'Simulation centers',
      'Medical libraries',
      'Residential complexes',
    ],
    website: 'https://www.aiims.edu',
    contactEmail: 'registrar@aiims.ac.in',
  },
];

export const studentAmbassadors: StudentAmbassador[] = [
  {
    id: 'sa1',
    name: 'Rajiv Sharma',
    university: 'Delhi University',
    universityId: 'u1',
    program: 'Computer Science',
    year: 3,
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150&h=150',
    about: 'I am passionate about helping Nepalese students navigate the university admission process and settle into campus life.',
    contactInfo: 'rajiv.s@studentambassador.du.ac.in',
  },
  {
    id: 'sa2',
    name: 'Priya Patel',
    university: 'IIT Bombay',
    universityId: 'u2',
    program: 'Electrical Engineering',
    year: 4,
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150&h=150',
    about: 'As an international student myself, I understand the challenges and opportunities of studying at IIT. Happy to help with queries!',
    contactInfo: 'priya.p@studentambassador.iitb.ac.in',
  },
  {
    id: 'sa3',
    name: 'Amir Khan',
    university: 'IIM Ahmedabad',
    universityId: 'u4',
    program: 'MBA',
    year: 2,
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150&h=150',
    about: 'I can provide insights into the competitive admission process, scholarship opportunities, and career prospects after an MBA from IIM.',
    contactInfo: 'amir.k@studentambassador.iima.ac.in',
  },
  {
    id: 'sa4',
    name: 'Lakshmi Rao',
    university: 'AIIMS',
    universityId: 'u6',
    program: 'MBBS',
    year: 5,
    profileImage: 'https://images.unsplash.com/photo-1593104547489-5cfb3839a3b5?auto=format&fit=crop&q=80&w=150&h=150',
    about: 'Medical education at AIIMS is challenging but rewarding. I help prospective students prepare for entrance exams and understand the curriculum.',
    contactInfo: 'lakshmi.r@studentambassador.aiims.ac.in',
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    universityId: 'u1',
    studentName: 'Suman Gurung',
    profileImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=150&h=150',
    rating: 4.8,
    comment: 'My experience at Delhi University has been amazing. The faculty is supportive, and there is a vibrant Nepalese student community. The scholarship opportunities for international students are excellent.',
    date: '2023-05-15',
    program: 'Computer Science',
    likes: 24,
  },
  {
    id: 'r2',
    universityId: 'u2',
    studentName: 'Binod Thapa',
    profileImage: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&q=80&w=150&h=150',
    rating: 4.7,
    comment: 'IIT Bombay offers cutting-edge technology education. The campus is beautiful, and the career opportunities after graduation are outstanding. The competitive environment pushes you to excel.',
    date: '2023-06-22',
    program: 'Mechanical Engineering',
    likes: 36,
  },
  {
    id: 'r3',
    universityId: 'u4',
    studentName: 'Maya Shrestha',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150&h=150',
    rating: 4.9,
    comment: 'The MBA program at IIM Ahmedabad is intense but transformative. As a Nepalese student, I received excellent support for visa processes and accommodation. The alumni network is incredibly valuable for career growth.',
    date: '2023-04-10',
    program: 'MBA',
    likes: 42,
  },
  {
    id: 'r4',
    universityId: 'u5',
    studentName: 'Rajan Paudel',
    profileImage: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=150&h=150',
    rating: 4.6,
    comment: 'Manipal University provides a global perspective on education. The campus facilities are world-class, and there are many Nepalese students. The faculty members are accessible and supportive.',
    date: '2023-07-05',
    program: 'Pharmacy',
    likes: 19,
  },
];
